on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      node_version:
        required: true
        type: string
      runner:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
    # Checkout
    - uses: actions/checkout@v4
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-
    # Setup NodeJS
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
    # Install dependencies
    - name: NPM CI
      run: npm ci --no-optional
    # Nuxt Generate
    - name: Nuxt Generate
      run: npm run generate
    - name: Store Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: src/.output/public
