# Deployment Workflow
name: 'Deployment'

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: 'build'
      node_version: '16.x'
      runner: 'ubuntu-latest'
  test:
    name: 'Test'
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      build_artifact_name: 'build'
      node_version: '16.x'
      runner: 'ubuntu-latest'
      test_base_url: 'http://localhost:3000'
      test_is_against_deployment: false
      test_report_artifact_name: 'test-ci-results'

  deploy_beta:
    name: 'Deploy Beta'
    needs: test
    uses: ./.github/workflows/deploy.yml
    with:
      aws_region: 'eu-west-1'
      build_artifact_name: 'build'
      is_production: false
      runner: 'ubuntu-latest'
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BETA_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.BETA_CLOUDFRONT_DISTRIBUTION_ID }}
      CLOUDFRONT_INVALIDATION_ACCESS_KEY_ID: ${{ secrets.CLOUDFRONT_INVALIDATION_ACCESS_KEY_ID }}
      CLOUDFRONT_INVALIDATION_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFRONT_INVALIDATION_SECRET_ACCESS_KEY }}
  deploy_production:
    name: 'Deploy Production'
    needs: deploy_beta
    uses: ./.github/workflows/deploy.yml
    with:
      aws_region: 'eu-west-1'
      build_artifact_name: 'build'
      is_production: true
      runner: 'ubuntu-latest'
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      CLOUDFRONT_INVALIDATION_ACCESS_KEY_ID: ${{ secrets.CLOUDFRONT_INVALIDATION_ACCESS_KEY_ID }}
      CLOUDFRONT_INVALIDATION_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFRONT_INVALIDATION_SECRET_ACCESS_KEY }}
