on:
  workflow_call:
    inputs:
      build_artifact_name:
        required: true
        type: string
      node_version:
        required: true
        type: string
      runner:
        required: true
        type: string
      test_base_url:
        required: true
        type: string
      test_is_against_deployment:
        required: true
        type: boolean
      test_report_artifact_name:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ inputs.runner }}
    container: 'mcr.microsoft.com/playwright:v1.21.1-focal'
    steps:
    # Checkout
    - uses: actions/checkout@v3
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-
    # Download previous build
    - uses: actions/download-artifact@v3
      if: ${{ inputs.test_is_against_deployment == false }}
      with:
        name: ${{ inputs.build_artifact_name }}
        path: dist
    # Setup NodeJS
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ inputs.node_version }}
    # Install dependencies
    - name: NPM CI
      run: npm ci
    - name: Run Playwright tests for feature
      if: ${{ inputs.test_is_against_deployment == false }}
      run: npm test --ignore-scripts
      env:
        CI: 'anything'
        TEST_BASE_URL: ${{ inputs.test_base_url }}
    - name: Run Playwright tests
      if: ${{ inputs.test_is_against_deployment }}
      run: npm test --ignore-scripts
      env:
        CI: 'anything'
        TEST_BASE_URL: ${{ inputs.test_base_url }}
        TEST_IS_AGAINST_DEPLOYMENT: 'anything'
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: ${{ inputs.test_report_artifact_name }}
        path: playwright-report/
        retention-days: 30
